"""Shared constants used across ETL modules."""

RATE_LIMIT_MIN_DELAY = 0.4
RATE_LIMIT_MAX_DELAY = 30.0
RATE_LIMIT_SUCCESS_STREAK = 3
RATE_LIMIT_SUCCESS_BACKOFF = 0.9
RATE_LIMIT_FAILURE_MULT = 1.4
RATE_LIMIT_RATE_LIMIT_MULT = 1.8
RATE_LIMIT_INTER_SEASON_CAP = 5.0

API_MIN_SLEEP = 0.5
API_MAX_SLEEP_CAP = 30.0
API_MAX_SLEEP_MULT = 8
API_SUCCESS_STREAK = 3
API_SUCCESS_BACKOFF = 0.9
API_FAILURE_MULT = 1.6

FEET_TO_INCHES = 12
INCHES_TO_CM = 2.54
LBS_TO_KG = 0.453592
NBA_FOUNDING_YEAR = 1946
SEASON_BOUNDARY_MONTH = 7
YEAR_SHORT_OFFSET = 2000
